---
language: java
dist: xenial

jdk:
- openjdk8

notifications:
  email: true

branches:
  except:
  - gh-pages

cache:
  directories:
  - "$HOME/.m2"

before_install:
- '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && openssl aes-256-cbc -K $encrypted_12345_key
  -iv $encrypted_12345_iv -in ibm-credentials.env.enc -out ibm-credentials.env -d || true'
install: true

script:
- mvn clean package -DskipTests

deploy:
  - provider: releases
    api_key: $GITHUB_OAUTH_TOKEN
    file_glob: true
    file:
      - target/java-sdk-template-*.jar
    skip_cleanup: true
    on:
      tags: true